theme: minima
title: Lori S. Shelly, Paralegal
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Accomplished paralegal with trust-building personality, enthusiastic attitude and experience in corporate governance, commercial closings, contract review and critical  thinking. Manages large and small projects from start to finish independently as well as highly confidential information with professionalism and integrity.

# social links
linkedin_username: https://www.linkedin.com/in/lorishelly/


show_excerpts: true # set to false to remove excerpts on the homepage
